from pathlib import Path

path = Path('src/app/App.tsx')
source = path.read_text()

old = """  const [storageNotice, setStorageNotice] = useState<string | null>(null)\n  const [shareNotice, setShareNotice] = useState<string | null>(null)\n\n  useEffect(() => {\n"""
new = """  const [storageNotice, setStorageNotice] = useState<string | null>(null)\n  const [shareNotice, setShareNotice] = useState<string | null>(null)\n  const [bootShare] = useState(() =>\n    typeof globalThis.location === 'undefined'\n      ? null\n      : parseSoundShareUrl(globalThis.location.href),\n  )\n\n  useEffect(() => {\n"""
if old not in source:
    raise SystemExit('missing boot state anchor')
source = source.replace(old, new, 1)

old = """    if (typeof globalThis.location !== 'undefined') {\n      const shared = parseSoundShareUrl(globalThis.location.href)\n      if (shared.state) {\n        initialSound = shared.state\n        const detail =\n          shared.messages.length > 0 ? ` ${shared.messages.join(' ')}` : ''\n        setShareNotice(\n          `Shared sound loaded. Audio remains Ready until you choose Start.${detail}`,\n        )\n        try {\n          globalThis.history?.replaceState(\n            null,\n            '',\n            stripSoundShareFragment(globalThis.location.href),\n          )\n        } catch {\n          // URL cleanup is cosmetic; successful import remains authoritative.\n        }\n      } else if (shared.code !== 'absent') {\n        setShareNotice(shared.messages.join(' '))\n      }\n    }\n"""
new = """    if (bootShare) {\n      if (bootShare.state) {\n        initialSound = bootShare.state\n        const detail =\n          bootShare.messages.length > 0\n            ? ` ${bootShare.messages.join(' ')}`\n            : ''\n        setShareNotice(\n          `Shared sound loaded. Audio remains Ready until you choose Start.${detail}`,\n        )\n        if (typeof globalThis.location !== 'undefined') {\n          try {\n            globalThis.history?.replaceState(\n              null,\n              '',\n              stripSoundShareFragment(globalThis.location.href),\n            )\n          } catch {\n            // URL cleanup is cosmetic; successful import remains authoritative.\n          }\n        }\n      } else if (bootShare.code !== 'absent') {\n        setShareNotice(bootShare.messages.join(' '))\n      }\n    }\n"""
if old not in source:
    raise SystemExit('missing share boot block')
source = source.replace(old, new, 1)

old = """    void bootstrap()\n\n    return () => {\n      cancelled = true\n      unsubscribe()\n      repositoryRef.current = null\n      engineRef.current = null\n      void engine.dispose()\n    }\n  }, [])\n"""
new = """    void bootstrap()\n\n    const handleShareHashChange = (): void => {\n      if (typeof globalThis.location === 'undefined') {\n        return\n      }\n      const shared = parseSoundShareUrl(globalThis.location.href)\n      if (shared.code === 'absent') {\n        return\n      }\n      if (!shared.state) {\n        if (!cancelled) {\n          setShareNotice(\n            shared.messages.join(' ') ||\n              'Shared sound payload could not be loaded safely.',\n          )\n        }\n        return\n      }\n\n      const next = shared.state\n      const detail =\n        shared.messages.length > 0 ? ` ${shared.messages.join(' ')}` : ''\n      setControlError(null)\n      setSoundState(next)\n      void Promise.all([\n        engine.resetSeed(next.seed),\n        engine.setSpectrumState(soundStateToSpectrumState(next)),\n        engine.setMasterGainDb(next.masterGainDb),\n        engine.setStereoWidth(next.stereoWidth),\n        engine.setAnimationState(soundStateToAnimationState(next)),\n      ])\n        .then(() => {\n          if (cancelled) {\n            return\n          }\n          const result = repository.saveSound(next)\n          if (!result.ok && result.diagnostic) {\n            setStorageNotice(result.diagnostic.message)\n          }\n          setShareNotice(\n            `Shared sound loaded. Loading did not start audio.${detail}`,\n          )\n          try {\n            globalThis.history?.replaceState(\n              null,\n              '',\n              stripSoundShareFragment(globalThis.location.href),\n            )\n          } catch {\n            // URL cleanup is cosmetic; successful import remains authoritative.\n          }\n        })\n        .catch((error) => {\n          if (!cancelled) {\n            setControlError(\n              `Shared sound state could not be applied: ${errorText(error)}`,\n            )\n          }\n        })\n    }\n\n    globalThis.addEventListener?.('hashchange', handleShareHashChange)\n\n    return () => {\n      cancelled = true\n      globalThis.removeEventListener?.('hashchange', handleShareHashChange)\n      unsubscribe()\n      repositoryRef.current = null\n      engineRef.current = null\n      void engine.dispose()\n    }\n  }, [bootShare])\n"""
if old not in source:
    raise SystemExit('missing effect cleanup anchor')
source = source.replace(old, new, 1)

path.write_text(source)
